[build]
  command = "mkdir -p $HOME/dotnet && tar zxf dotnet-sdk-3.0.100-preview5-011568-linux-x64.tar.gz -C $HOME/dotnet && export DOTNET_ROOT=$HOME/dotnet && export PATH=$PATH:$HOME/dotnet && dotnet publish -c release -o dist"
  publish = "dist"
