[build]
  command = "wget https://download.visualstudio.microsoft.com/download/pr/7e4b403c-34b3-4b3e-807c-d064a7857fe8/95c738f08e163f27867e38c602a433a1/dotnet-sdk-3.0.100-preview5-011568-linux-x64.tar.gz && mkdir -p $HOME/dotnet && tar zxf dotnet-sdk-3.0.100-preview5-011568-linux-x64.tar.gz -C $HOME/dotnet && export DOTNET_ROOT=$HOME/dotnet && export PATH=$PATH:$HOME/dotnet && dotnet publish -c release -o dist"
  publish = "dist"
