version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0.100-preview5-buster

    # working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Release
          command: dotnet publish -c release -o dist
