version: 2.1
jobs:
  build:
    docker:
      - image: microsoft/dotnet:3-sdk

    # working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Release
          command: dotnet publish -c release -o dist
