version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0.100-preview5-buster
    working_directory: ~/dist
    steps:
      - checkout
      - run:
          name: Release
          command: dotnet publish -c release -o release
      - store_artifacts:
          path: /tmp/artifacts
          destination: build
  deploy:
    docker:
      - image: node:8.16.0-jessie
    working_directory: ~/dist
    steps:
      - run:
          name: Install Netlify CLI
          command: 'npm install -g netlify-cli@latest'
      - run:
          name: Deploy to Netlify
          command: 'netlify deploy'
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - develop
                - /feature-.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

